"""add news_articles

Revision ID: 457269cc18e0
Revises: c9e5d3f2a1b6
Create Date: 2026-05-05 20:11:08.532277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '457269cc18e0'
down_revision: Union[str, None] = 'c9e5d3f2a1b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_articles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('guid', sa.String(length=500), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('feed_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_articles_category'), 'news_articles', ['category'], unique=False)
    op.create_index(op.f('ix_news_articles_guid'), 'news_articles', ['guid'], unique=True)
    op.create_index(op.f('ix_news_articles_published_at'), 'news_articles', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_articles_source'), 'news_articles', ['source'], unique=False)
    op.create_index('ix_news_published', 'news_articles', ['published_at'], unique=False)
    op.drop_index(op.f('ix_trip_note_start_date'), table_name='trip_notes')
    op.drop_constraint(op.f('uq_trip_note_start_date'), 'trip_notes', type_='unique')
    op.create_index(op.f('ix_trip_notes_start_date'), 'trip_notes', ['start_date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_notes_start_date'), table_name='trip_notes')
    op.create_unique_constraint(op.f('uq_trip_note_start_date'), 'trip_notes', ['start_date'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_trip_note_start_date'), 'trip_notes', ['start_date'], unique=False)
    op.drop_index('ix_news_published', table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_source'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_published_at'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_guid'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_category'), table_name='news_articles')
    op.drop_table('news_articles')
    # ### end Alembic commands ###
