"""phase2_location_points

Revision ID: 5044ada9f866
Revises: 77b853f4a31d
Create Date: 2026-04-28 22:24:53.043350

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers
revision: str = "5044ada9f866"
down_revision: str | None = "77b853f4a31d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "location_points",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("timestamp_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=10, scale=7), nullable=False),
        sa.Column("longitude", sa.Numeric(precision=10, scale=7), nullable=False),
        sa.Column("accuracy_m", sa.Integer(), nullable=True),
        sa.Column("altitude_m", sa.Integer(), nullable=True),
        sa.Column("activity_type", sa.String(length=30), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("source_file", sa.String(length=255), nullable=True),
        sa.Column("latitude_e7", sa.BigInteger(), nullable=False),
        sa.Column("longitude_e7", sa.BigInteger(), nullable=False),
        sa.Column("dedup_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_location_points_activity_type"), "location_points", ["activity_type"], unique=False
    )
    op.create_index(
        op.f("ix_location_points_dedup_hash"), "location_points", ["dedup_hash"], unique=True
    )
    op.create_index(op.f("ix_location_points_source"), "location_points", ["source"], unique=False)
    op.create_index(
        op.f("ix_location_points_timestamp_utc"), "location_points", ["timestamp_utc"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_location_points_timestamp_utc"), table_name="location_points")
    op.drop_index(op.f("ix_location_points_source"), table_name="location_points")
    op.drop_index(op.f("ix_location_points_dedup_hash"), table_name="location_points")
    op.drop_index(op.f("ix_location_points_activity_type"), table_name="location_points")
    op.drop_table("location_points")
    # ### end Alembic commands ###
