"""phase1_investment_transactions_positions

Revision ID: 77b853f4a31d
Revises: cfb9d1cc7135
Create Date: 2026-04-28 20:47:05.120333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '77b853f4a31d'
down_revision: Union[str, None] = 'cfb9d1cc7135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_positions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('sub_account_code', sa.String(length=20), nullable=False),
    sa.Column('statement_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('average_unit_cost', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('book_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('market_price', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('market_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('portfolio_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('source_format', sa.String(length=50), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('dedup_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_positions_account_id'), 'investment_positions', ['account_id'], unique=False)
    op.create_index(op.f('ix_investment_positions_dedup_hash'), 'investment_positions', ['dedup_hash'], unique=True)
    op.create_index(op.f('ix_investment_positions_statement_date'), 'investment_positions', ['statement_date'], unique=False)
    op.create_index(op.f('ix_investment_positions_sub_account_code'), 'investment_positions', ['sub_account_code'], unique=False)
    op.create_index(op.f('ix_investment_positions_symbol'), 'investment_positions', ['symbol'], unique=False)
    op.create_table('investment_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('sub_account_code', sa.String(length=20), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('operation', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('statement_date', sa.Date(), nullable=False),
    sa.Column('source_format', sa.String(length=50), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('dedup_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_transactions_account_id'), 'investment_transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_investment_transactions_dedup_hash'), 'investment_transactions', ['dedup_hash'], unique=True)
    op.create_index(op.f('ix_investment_transactions_statement_date'), 'investment_transactions', ['statement_date'], unique=False)
    op.create_index(op.f('ix_investment_transactions_sub_account_code'), 'investment_transactions', ['sub_account_code'], unique=False)
    op.create_index(op.f('ix_investment_transactions_symbol'), 'investment_transactions', ['symbol'], unique=False)
    op.create_index(op.f('ix_investment_transactions_transaction_date'), 'investment_transactions', ['transaction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investment_transactions_transaction_date'), table_name='investment_transactions')
    op.drop_index(op.f('ix_investment_transactions_symbol'), table_name='investment_transactions')
    op.drop_index(op.f('ix_investment_transactions_sub_account_code'), table_name='investment_transactions')
    op.drop_index(op.f('ix_investment_transactions_statement_date'), table_name='investment_transactions')
    op.drop_index(op.f('ix_investment_transactions_dedup_hash'), table_name='investment_transactions')
    op.drop_index(op.f('ix_investment_transactions_account_id'), table_name='investment_transactions')
    op.drop_table('investment_transactions')
    op.drop_index(op.f('ix_investment_positions_symbol'), table_name='investment_positions')
    op.drop_index(op.f('ix_investment_positions_sub_account_code'), table_name='investment_positions')
    op.drop_index(op.f('ix_investment_positions_statement_date'), table_name='investment_positions')
    op.drop_index(op.f('ix_investment_positions_dedup_hash'), table_name='investment_positions')
    op.drop_index(op.f('ix_investment_positions_account_id'), table_name='investment_positions')
    op.drop_table('investment_positions')
    # ### end Alembic commands ###
