"""add_location_visits_and_activities

Revision ID: 93cf1ed7b005
Revises: d1f2e3a4b5c6
Create Date: 2026-05-04 11:56:01.706262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '93cf1ed7b005'
down_revision: Union[str, None] = 'd1f2e3a4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_activities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tz_offset_minutes', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.String(length=60), nullable=True),
    sa.Column('distance_meters', sa.Float(), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('start_lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('start_lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('end_lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('end_lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('dedup_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_hash', name='uq_location_activity_dedup')
    )
    op.create_index(op.f('ix_location_activities_dedup_hash'), 'location_activities', ['dedup_hash'], unique=True)
    op.create_index(op.f('ix_location_activities_start_time'), 'location_activities', ['start_time'], unique=False)
    op.create_index('ix_location_activity_start', 'location_activities', ['start_time'], unique=False)
    op.create_index('ix_location_activity_type', 'location_activities', ['activity_type'], unique=False)
    op.create_table('location_visits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tz_offset_minutes', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('lng', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('lat_e7', sa.Integer(), nullable=False),
    sa.Column('lng_e7', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.String(length=255), nullable=True),
    sa.Column('semantic_type', sa.String(length=60), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('dedup_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_hash', name='uq_location_visit_dedup')
    )
    op.create_index('ix_location_visit_semantic', 'location_visits', ['semantic_type'], unique=False)
    op.create_index('ix_location_visit_start', 'location_visits', ['start_time'], unique=False)
    op.create_index(op.f('ix_location_visits_dedup_hash'), 'location_visits', ['dedup_hash'], unique=True)
    op.create_index(op.f('ix_location_visits_place_id'), 'location_visits', ['place_id'], unique=False)
    op.create_index(op.f('ix_location_visits_start_time'), 'location_visits', ['start_time'], unique=False)
    op.create_index(op.f('ix_oauth_tokens_provider'), 'oauth_tokens', ['provider'], unique=False)
    op.create_index(op.f('ix_oauth_tokens_service'), 'oauth_tokens', ['service'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oauth_tokens_service'), table_name='oauth_tokens')
    op.drop_index(op.f('ix_oauth_tokens_provider'), table_name='oauth_tokens')
    op.drop_index(op.f('ix_location_visits_start_time'), table_name='location_visits')
    op.drop_index(op.f('ix_location_visits_place_id'), table_name='location_visits')
    op.drop_index(op.f('ix_location_visits_dedup_hash'), table_name='location_visits')
    op.drop_index('ix_location_visit_start', table_name='location_visits')
    op.drop_index('ix_location_visit_semantic', table_name='location_visits')
    op.drop_table('location_visits')
    op.drop_index('ix_location_activity_type', table_name='location_activities')
    op.drop_index('ix_location_activity_start', table_name='location_activities')
    op.drop_index(op.f('ix_location_activities_start_time'), table_name='location_activities')
    op.drop_index(op.f('ix_location_activities_dedup_hash'), table_name='location_activities')
    op.drop_table('location_activities')
    # ### end Alembic commands ###
