"""phase3_4_5_emails_calendar_photos_etc

Revision ID: c60cb4eb8b9f
Revises: a1b2c3d4e5f6
Create Date: 2026-05-02 01:21:52.228855

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers
revision: str = 'c60cb4eb8b9f'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('gcal_id', sa.String(length=200), nullable=False),
    sa.Column('calendar_id', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('organizer_email', sa.String(length=255), nullable=True),
    sa.Column('attendees', postgresql.ARRAY(sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('html_link', sa.Text(), nullable=True),
    sa.Column('recurring_event_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_events_calendar_id'), 'calendar_events', ['calendar_id'], unique=False)
    op.create_index(op.f('ix_calendar_events_gcal_id'), 'calendar_events', ['gcal_id'], unique=True)
    op.create_index(op.f('ix_calendar_events_start_at'), 'calendar_events', ['start_at'], unique=False)
    op.create_index(op.f('ix_calendar_events_user_email'), 'calendar_events', ['user_email'], unique=False)
    op.create_index('ix_calevt_user_start', 'calendar_events', ['user_email', 'start_at'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('person_id', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('given_name', sa.String(length=100), nullable=True),
    sa.Column('family_name', sa.String(length=100), nullable=True),
    sa.Column('emails', postgresql.ARRAY(sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('phones', postgresql.ARRAY(sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('addresses', postgresql.ARRAY(sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('organizations', postgresql.ARRAY(sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_person_id'), 'contacts', ['person_id'], unique=True)
    op.create_index(op.f('ix_contacts_user_email'), 'contacts', ['user_email'], unique=False)
    op.create_index('ix_contacts_user_name', 'contacts', ['user_email', 'display_name'], unique=False)
    op.create_table('drive_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('drive_id', sa.String(length=200), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=150), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('starred', sa.Boolean(), nullable=False),
    sa.Column('trashed', sa.Boolean(), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('owner_email', sa.String(length=255), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('web_view_link', sa.Text(), nullable=True),
    sa.Column('parents', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drive_files_drive_id'), 'drive_files', ['drive_id'], unique=True)
    op.create_index(op.f('ix_drive_files_mime_type'), 'drive_files', ['mime_type'], unique=False)
    op.create_index(op.f('ix_drive_files_modified_time'), 'drive_files', ['modified_time'], unique=False)
    op.create_index(op.f('ix_drive_files_user_email'), 'drive_files', ['user_email'], unique=False)
    op.create_index('ix_drive_user_modified', 'drive_files', ['user_email', 'modified_time'], unique=False)
    op.create_table('emails',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('gmail_id', sa.String(length=50), nullable=False),
    sa.Column('thread_id', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('sender', sa.Text(), nullable=False),
    sa.Column('sender_email', sa.String(length=255), nullable=False),
    sa.Column('recipients', postgresql.ARRAY(sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('snippet', sa.String(length=500), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('labels', postgresql.ARRAY(sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('has_attachments', sa.Boolean(), nullable=False),
    sa.Column('is_unread', sa.Boolean(), nullable=False),
    sa.Column('size_estimate', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emails_gmail_id'), 'emails', ['gmail_id'], unique=True)
    op.create_index(op.f('ix_emails_sender_email'), 'emails', ['sender_email'], unique=False)
    op.create_index('ix_emails_sender_email_sent_at', 'emails', ['sender_email', 'sent_at'], unique=False)
    op.create_index(op.f('ix_emails_sent_at'), 'emails', ['sent_at'], unique=False)
    op.create_index(op.f('ix_emails_thread_id'), 'emails', ['thread_id'], unique=False)
    op.create_index(op.f('ix_emails_user_email'), 'emails', ['user_email'], unique=False)
    op.create_index('ix_emails_user_email_sent_at', 'emails', ['user_email', 'sent_at'], unique=False)
    op.create_table('health_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('metric', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('raw_meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_email', 'date', 'metric', 'source', name='uq_health_user_date_metric_source')
    )
    op.create_index('ix_health_metric_date', 'health_metrics', ['metric', 'date'], unique=False)
    op.create_index(op.f('ix_health_metrics_date'), 'health_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_health_metrics_metric'), 'health_metrics', ['metric'], unique=False)
    op.create_index(op.f('ix_health_metrics_user_email'), 'health_metrics', ['user_email'], unique=False)
    op.create_index('ix_health_user_date', 'health_metrics', ['user_email', 'date'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('media_id', sa.String(length=200), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creation_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('is_video', sa.Boolean(), nullable=False),
    sa.Column('video_duration_ms', sa.Integer(), nullable=True),
    sa.Column('camera_make', sa.String(length=100), nullable=True),
    sa.Column('camera_model', sa.String(length=100), nullable=True),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('product_url', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('altitude_m', sa.Float(), nullable=True),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('exif_data', sa.JSON(), nullable=True),
    sa.Column('faces_count', sa.Integer(), nullable=True),
    sa.Column('faces_data', sa.JSON(), nullable=True),
    sa.Column('clip_embedding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_creation_time'), 'photos', ['creation_time'], unique=False)
    op.create_index('ix_photos_geo', 'photos', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_photos_media_id'), 'photos', ['media_id'], unique=True)
    op.create_index('ix_photos_user_creation', 'photos', ['user_email', 'creation_time'], unique=False)
    op.create_index(op.f('ix_photos_user_email'), 'photos', ['user_email'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('task_id', sa.String(length=200), nullable=False),
    sa.Column('tasklist_id', sa.String(length=200), nullable=False),
    sa.Column('tasklist_title', sa.String(length=255), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_due_at'), 'tasks', ['due_at'], unique=False)
    op.create_index(op.f('ix_tasks_task_id'), 'tasks', ['task_id'], unique=True)
    op.create_index(op.f('ix_tasks_tasklist_id'), 'tasks', ['tasklist_id'], unique=False)
    op.create_index('ix_tasks_user_due', 'tasks', ['user_email', 'due_at'], unique=False)
    op.create_index(op.f('ix_tasks_user_email'), 'tasks', ['user_email'], unique=False)
    op.create_table('youtube_activities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('activity_id', sa.String(length=200), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('video_id', sa.String(length=50), nullable=True),
    sa.Column('video_title', sa.Text(), nullable=True),
    sa.Column('channel_id', sa.String(length=50), nullable=True),
    sa.Column('channel_title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_youtube_activities_activity_id'), 'youtube_activities', ['activity_id'], unique=True)
    op.create_index(op.f('ix_youtube_activities_activity_type'), 'youtube_activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_youtube_activities_published_at'), 'youtube_activities', ['published_at'], unique=False)
    op.create_index(op.f('ix_youtube_activities_user_email'), 'youtube_activities', ['user_email'], unique=False)
    op.create_index(op.f('ix_youtube_activities_video_id'), 'youtube_activities', ['video_id'], unique=False)
    op.create_index('ix_yt_user_published', 'youtube_activities', ['user_email', 'published_at'], unique=False)
    op.drop_index(op.f('ix_oauth_tokens_provider'), table_name='oauth_tokens')
    op.drop_index(op.f('ix_oauth_tokens_service'), table_name='oauth_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_oauth_tokens_service'), 'oauth_tokens', ['service'], unique=False)
    op.create_index(op.f('ix_oauth_tokens_provider'), 'oauth_tokens', ['provider'], unique=False)
    op.drop_index('ix_yt_user_published', table_name='youtube_activities')
    op.drop_index(op.f('ix_youtube_activities_video_id'), table_name='youtube_activities')
    op.drop_index(op.f('ix_youtube_activities_user_email'), table_name='youtube_activities')
    op.drop_index(op.f('ix_youtube_activities_published_at'), table_name='youtube_activities')
    op.drop_index(op.f('ix_youtube_activities_activity_type'), table_name='youtube_activities')
    op.drop_index(op.f('ix_youtube_activities_activity_id'), table_name='youtube_activities')
    op.drop_table('youtube_activities')
    op.drop_index(op.f('ix_tasks_user_email'), table_name='tasks')
    op.drop_index('ix_tasks_user_due', table_name='tasks')
    op.drop_index(op.f('ix_tasks_tasklist_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_task_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_at'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_photos_user_email'), table_name='photos')
    op.drop_index('ix_photos_user_creation', table_name='photos')
    op.drop_index(op.f('ix_photos_media_id'), table_name='photos')
    op.drop_index('ix_photos_geo', table_name='photos')
    op.drop_index(op.f('ix_photos_creation_time'), table_name='photos')
    op.drop_table('photos')
    op.drop_index('ix_health_user_date', table_name='health_metrics')
    op.drop_index(op.f('ix_health_metrics_user_email'), table_name='health_metrics')
    op.drop_index(op.f('ix_health_metrics_metric'), table_name='health_metrics')
    op.drop_index(op.f('ix_health_metrics_date'), table_name='health_metrics')
    op.drop_index('ix_health_metric_date', table_name='health_metrics')
    op.drop_table('health_metrics')
    op.drop_index('ix_emails_user_email_sent_at', table_name='emails')
    op.drop_index(op.f('ix_emails_user_email'), table_name='emails')
    op.drop_index(op.f('ix_emails_thread_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_sent_at'), table_name='emails')
    op.drop_index('ix_emails_sender_email_sent_at', table_name='emails')
    op.drop_index(op.f('ix_emails_sender_email'), table_name='emails')
    op.drop_index(op.f('ix_emails_gmail_id'), table_name='emails')
    op.drop_table('emails')
    op.drop_index('ix_drive_user_modified', table_name='drive_files')
    op.drop_index(op.f('ix_drive_files_user_email'), table_name='drive_files')
    op.drop_index(op.f('ix_drive_files_modified_time'), table_name='drive_files')
    op.drop_index(op.f('ix_drive_files_mime_type'), table_name='drive_files')
    op.drop_index(op.f('ix_drive_files_drive_id'), table_name='drive_files')
    op.drop_table('drive_files')
    op.drop_index('ix_contacts_user_name', table_name='contacts')
    op.drop_index(op.f('ix_contacts_user_email'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_person_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index('ix_calevt_user_start', table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_user_email'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_start_at'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_gcal_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_calendar_id'), table_name='calendar_events')
    op.drop_table('calendar_events')
    # ### end Alembic commands ###
