"""phase1_credit_card_transactions

Revision ID: cfb9d1cc7135
Revises: c84411d473b8
Create Date: 2026-04-28 20:37:39.572757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'cfb9d1cc7135'
down_revision: Union[str, None] = 'c84411d473b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_card_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('card_number_masked', sa.String(length=50), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('posting_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cashback_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('section', sa.String(length=30), nullable=False),
    sa.Column('source_format', sa.String(length=50), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('statement_date', sa.Date(), nullable=True),
    sa.Column('dedup_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_card_transactions_account_id'), 'credit_card_transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_credit_card_transactions_card_number_masked'), 'credit_card_transactions', ['card_number_masked'], unique=False)
    op.create_index(op.f('ix_credit_card_transactions_dedup_hash'), 'credit_card_transactions', ['dedup_hash'], unique=True)
    op.create_index(op.f('ix_credit_card_transactions_transaction_date'), 'credit_card_transactions', ['transaction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credit_card_transactions_transaction_date'), table_name='credit_card_transactions')
    op.drop_index(op.f('ix_credit_card_transactions_dedup_hash'), table_name='credit_card_transactions')
    op.drop_index(op.f('ix_credit_card_transactions_card_number_masked'), table_name='credit_card_transactions')
    op.drop_index(op.f('ix_credit_card_transactions_account_id'), table_name='credit_card_transactions')
    op.drop_table('credit_card_transactions')
    # ### end Alembic commands ###
